
---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "`r Sys.getenv('USER')`"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
---
  



How I gathered pan disease cohort source data

```{r eval=FALSE, include=TRUE}


cd /private/groups/treehouse/working-projects/hbeale/ckcc2_2023_07/
mkdir -p special_run_no_curation
tert_output_base=/private/groups/treehouse/archive/downstream


f="original_tertiary_locations_as_of_2023_10_25-10_27_50_2023.tsv"
cat $f | grep -v ^Sample | while read Sample compendium_version recorded_protocol_version; 
do 

tert_output=${Sample}/tertiary/treehouse-care-0.17.1.0-8107fe7.4/compendium-v11_polya

echo $Sample $tert_output

mkdir -p special_run_no_curation/${tert_output}

cp ${tert_output_base}/${tert_output}/2.0.json ${tert_output_base}/${tert_output}/2.2.json ${tert_output_base}/${tert_output}/4.0.json  special_run_no_curation/${tert_output}

done


tar -cvzf special_run_no_curation.gz special_run_no_curation


```

```{r setup}

library(tidyverse)
library(jsonlite)
library(janitor)

```

# Get paths
```{r}
tert_data_base_dir <- "../../../ckcc2/2023 reboot/data/pan_disease_from_special_run_no_curation"


paths_file <- "../input_data/original_tertiary_locations_as_of_2023_10_25-10_27_50_2023.tsv"
samples_file <- "../input_data/ckcc2_samples_and_metadata_from_redcap_2023.10.24_13.26.34.tsv"

paths_raw <- read_tsv(paths_file,
                      col_types = cols(.default = "c")) %>%
  mutate(tertiary_path = file.path(
    tert_data_base_dir,
    Sample,
    "/tertiary/treehouse-care-0.17.1.0-8107fe7.4/compendium-v11_polya"))

nrow(paths_raw)

project_samples <- read_tsv(samples_file,
                      col_types = cols(.default = "c"))
nrow(project_samples)

# reminder; there are more lines in the paths_raw tibble than
# in the project_samples tibble because some samples have
# multiple tert outputs


# check whether all samples are present in both data sources
# if both groups are identical,  result will be "character(0)"
setdiff(paths_raw$Sample, project_samples$THid)
setdiff(project_samples$THid, paths_raw$Sample)

tertiary_output_locations <- paths_raw %>%
  select(sample_id = Sample, tertiary_path)
```


# Load cohorts
```{r}

# TH34_1149_S02 has no pd cohorts
# TH34_1150_S02 has samples in all 4 pd cohorts 

load_pan_disease_cohorts <- function(this_tert_data_dir) {
  # this_tert_data_dir <- paths_raw$tertiary_path[4]
  j1_file <- file.path(this_tert_data_dir, "2.0.json")
  j2_file <- gsub("2.0.json", "2.2.json", j1_file)
  
  j1 <- fromJSON(j1_file)
  j2 <- fromJSON(j2_file)
  
  cohort_list<-list(
    j1["first_degree_mcs_cohort"][[1]],
    j1["pandisease_samples"][[1]],
    j2["diagnosed_disease_cohort"][[1]],
    j2["first_and_second_degree_mcs_cohort"][[1]]
  )
  
  names(cohort_list)=c("first_degree_mcs_cohort", "pandisease_samples", "diagnosed_disease_cohort", "first_and_second_degree_mcs_cohort")
  cohort_tibble <- map_df(cohort_list, ~as_tibble(.x), .id="id") %>%
    mutate(TH_id = str_extract(this_tert_data_dir, "TH[R]?[0-9]{2}_[0-9]{4}_S[0-9]{2}"))
  return(cohort_tibble)
}

cohort_members <- lapply(paths_raw$tertiary_path, load_pan_disease_cohorts) %>%
  bind_rows() %>% 
  rename(cohort=id, cohort_member=value)
```

# Save cohorts
```{r}


output_name <- paste0("../input_data/v11_automated_pan_disease_cohort_members_", format(Sys.time(), "%Y_%m_%d-%H_%M_%S_%Y"), ".tsv")

output_name

write_tsv(cohort_members, output_name)

```
