---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "`r Sys.getenv('USER')`"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    toc: yes
---
  


```{r setup, include = FALSE}

library(tidyverse)
library(janitor) 
library(gridExtra)
library(cowplot)
library(ggforce)

```



```{r}

outliers <- read_tsv("../input_data/druggable_outliers_from_treehouse_and_other_cohorts_2023_11_09-13_46_32_2023.tsv") %>%
  mutate(high_level_cohort = ifelse(str_detect(comparison_cohort, "Treehouse"),
                                    "Treehouse",
                                    comparison_cohort))

         
         
```



# COMPARE DISTRIBUTIONS FOR FOR OUTLIERS ACROSS COHORTS

```{r}

outlier_genes_detected <- unique(outliers$gene)

expr <- read_tsv("../input_data/druggable_TumorCompendium_v11_PolyA_hugo_log2tpm_58581genes_2020-04-09.tsv.gz") %>%
  rename(Sample_ID = TH_id) %>%
  filter(Gene %in% outlier_genes_detected)

stanford_samples  <- read_tsv("../gather_input_data/comparison_to_non_CARE_cohorts/data/TH03_TH34_rollup.sample_list.txt",
                              col_names = "Sample_ID") %>%
  mutate(cohort = "TH03_TH34")

TCGA_samples  <- read_tsv("../gather_input_data/comparison_to_non_CARE_cohorts/data/TCGA_rollup.sample_list.txt",
                              col_names = "Sample_ID") %>%
  mutate(cohort = "TCGA")

PEDAYA_samples  <- read_tsv("../gather_input_data/comparison_to_non_CARE_cohorts/data/PEDAYA_rollup.sample_list.txt",
                              col_names = "Sample_ID") %>%
  mutate(cohort = "PEDAYA")

pan_cancer_samples <- expr %>%
  select(Sample_ID) %>%
  distinct() %>%
  mutate(cohort = "Treehouse_pc")


samples_in_cohorts <- bind_rows(
  stanford_samples,
  TCGA_samples,
  PEDAYA_samples,
  pan_cancer_samples)


tabyl(samples_in_cohorts,
      cohort)
```


# expression in samples not in the compendium
```{r}

rsem_path <- "../input_data/non_compendium_expression"

gene_name_conversion <- read_tsv(file.path(rsem_path,
                                           "EnsGeneID_Hugo_Observed_Conversions.txt"))
relevant_gene_name_conversion <- gene_name_conversion %>%
  filter(HugoID %in% outlier_genes_detected)

rsem_kitchen_sink_data <- tibble(file_name = list.files(
  path = rsem_path,
  pattern = "_rsem_genes.results")) %>%
  rowwise() %>%
  mutate(rsem_raw = list(read_tsv(file.path(rsem_path, file_name),
                                     show_col_types = FALSE
                                     ))) %>%
  unnest(rsem_raw) %>%
  filter(gene_id %in% relevant_gene_name_conversion$EnsGeneID) %>%
  mutate(Sample_ID = str_extract(file_name, "TH[R]?[0-9]{2}_[0-9]{4}_S[0-9]{2}")) %>%
  left_join(relevant_gene_name_conversion, 
            by=c("gene_id"="EnsGeneID")) %>%
    group_by(Sample_ID, HugoID) %>%
    summarize(sum_TPM = sum(TPM),
              n=n()) %>%
    mutate(log2TPM1 = log2(sum_TPM +1))

table(rsem_kitchen_sink_data$n)

patient_expression_from_rsem_files <- rsem_kitchen_sink_data %>%
  select(gene = HugoID,
         log2TPM1,
         Sample_ID)

patient_expression_from_compendia <- outliers %>%
  select(Sample_ID, gene) %>%
  distinct() %>%
  left_join(expr, 
            by=c("Sample_ID", "gene"="Gene")) %>%
  na.omit() # excludes samples not in compendium

patient_expression <- bind_rows(
  patient_expression_from_rsem_files,
  patient_expression_from_compendia)
  
length(outlier_genes_detected)

```


```{r}
outliers$Sample_ID[ ! outliers$Sample_ID %in% expr$Sample_ID] %>% unique()
```

outliers
```{r}

patient_expression

```



```{r}
# How many colors to i need

outliers %>%
  group_by(gene) %>%
  summarize(n_samples = length(unique(Sample_ID))) %>%
  arrange(desc(n_samples))


```
# Calculate statistics for each cohort
```{r}



cohort_thresholds_raw <- left_join(samples_in_cohorts,
                                   expr,
                                   by=c("Sample_ID")) %>%
  group_by(Gene, cohort) %>%
  summarize(q25 = quantile(log2TPM1, 0.25),
            median = median(log2TPM1),
            q75 = quantile(log2TPM1, 0.75),
            IQR = q75-q25,
            up_outlier_threshold = q75 + (1.5*IQR))
  
```

# pediatric vs TCGA for one gene
```{r}

this_gene <- "ETV1"

cohort_thresholds_raw %>%
  filter(Gene == this_gene) %>%
  group_by(Gene) %>%
  pivot_longer(c(-Gene, -cohort)) %>%
  pivot_wider(names_from = cohort, values_from = value) %>%
  mutate(change_in_ped_relative_to_TCGA = 
              (PEDAYA - TCGA) / TCGA,
         change_in_treehouse_relative_to_TCGA = 
            (Treehouse_pc - TCGA) / Treehouse_pc) %>%
  select(-TH03_TH34)


# is the biggest change to the median or to the IQR?
  summarize(q_25_change_in_ped_relative_to_TCGA = 
              (q25[cohort == "PEDAYA"] - q25[cohort == "TCGA"]) / q25[cohort == "TCGA"])

```
# for all genes
```{r}

cohort_thresholds <- cohort_thresholds_raw %>%
  pivot_longer(c(-Gene, -cohort)) %>%
  pivot_wider(names_from = cohort, values_from = value) %>%
  mutate(change_in_ped_relative_to_TCGA = 
              (PEDAYA - TCGA) / TCGA,
         change_in_treehouse_relative_to_TCGA = 
            (Treehouse_pc - TCGA) / Treehouse_pc) 


ggplot(cohort_thresholds) +
  geom_point(aes(x=change_in_ped_relative_to_TCGA,
                 y=change_in_treehouse_relative_to_TCGA,
                 color = name)) +
  scale_color_brewer(palette = "Set1")
             

cohort_thresholds %>%
  filter(name %in% c("median", "IQR")) %>%
  select(Gene, name, change_in_ped_relative_to_TCGA) %>%
  pivot_wider(names_from = name,
              values_from = change_in_ped_relative_to_TCGA) %>%
  ggplot + 
  geom_point(aes(x=median, y=IQR)) + 
  ggtitle("fraction change_in_ped_relative_to_TCGA")


```



```{r fig.height=12, fig.width=8}

lapply(outlier_genes_detected, function(this_gene){
  # this_gene <- "BCL6"
  relevant_patient_expression <- patient_expression %>%
    filter(gene == this_gene) %>%
    filter(Sample_ID %in% (outliers %>%
                             filter(gene == this_gene) %>% 
                             pull(Sample_ID)))
                           
  
  one_gene_expr_per_cohort <- left_join(samples_in_cohorts,
                                        expr %>%
                                          filter(Gene == this_gene))
   
  outlier_table <- outliers %>%
    select(Sample_ID, gene, comparison_cohort) %>%
    mutate(found = TRUE) %>%
    pivot_wider(names_from = comparison_cohort,
                values_from = found,
                values_fill = FALSE) %>%
    filter(gene == this_gene) %>%
    select(-Treehouse_pd) %>%
    left_join(relevant_patient_expression,
              by = c("Sample_ID", "gene")) %>%
    mutate(log2TPM1 = round(log2TPM1, 3))
  
  outlier_table_long <- outlier_table %>%
    pivot_longer(cols = c(-Sample_ID, -log2TPM1, -gene),
                 names_to = "cohort",
                 values_to = "outlier") %>%
    mutate(outlier_status = c("non outlier", "outlier")[1+outlier])
  
 cohort_thresholds <-  one_gene_expr_per_cohort %>%
  group_by(cohort) %>%
  summarize(q25 = quantile(log2TPM1, 0.25),
            median = median(log2TPM1),
            q75 = quantile(log2TPM1, 0.75),
            IQR = q75-q25,
            up_outlier_threshold = q75 + (1.5*IQR)) %>%
  pivot_longer(-cohort) %>%
  mutate(value = round(value, 2)) %>%
  pivot_wider()
  
  
   p1 <- ggplot(one_gene_expr_per_cohort) +
    geom_histogram(aes(x=log2TPM1)) +
    geom_vline(data = outlier_table_long,
               aes(xintercept = log2TPM1,
                   color = Sample_ID,
                   lty = outlier_status)) +
    scale_color_brewer(palette = "Set1") +
    facet_col(~cohort, scales = "free_y") +
  ggtitle(this_gene)
  
  p2 <- ggplot(one_gene_expr_per_cohort) +
    geom_boxplot(aes(x=log2TPM1)) +
    geom_vline(data = outlier_table_long,
               aes(xintercept = log2TPM1,
                   color = Sample_ID,
                   lty = outlier_status)) +
    scale_color_brewer(palette = "Set1") +
    facet_col(~cohort) 
  
  t1 <- tableGrob(outlier_table, theme=ttheme_minimal(), 
                  rows=NULL)  # transform into a tableGrob
  
  t2 <- tableGrob(cohort_thresholds, theme=ttheme_minimal(), 
                  rows=NULL)  # transform into a tableGrob
  
  plot_grid(p1, p2, t1, t2,
                     ncol = 1)
})



```


# table for annotating TCGA vs Treehouse pc
```{r}

outlier_table_for_annotation <- outliers %>%
    select(Sample_ID, gene, comparison_cohort) %>%
    mutate(found = TRUE) %>%
    pivot_wider(names_from = comparison_cohort,
                values_from = found,
                values_fill = FALSE) %>%
  arrange(gene) %>%
  mutate(TCGA_not_treehouse_pc = TCGA & ! Treehouse_pc) %>%
  select(gene, Sample_ID, TCGA, Treehouse_pc, TCGA_not_treehouse_pc, everything())
  
write_tsv(outlier_table_for_annotation, "../gather_input_data/comparison_to_non_CARE_cohorts/TCGA_vs_TH_outlier_table_for_annotation.tsv")

  

```

