---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "`r Sys.getenv('USER')`"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
---
  

version 2023.11.27_11.25.57 adds per-patient analysis


```{r setup, include = FALSE}

library(tidyverse)
library(janitor)
library(khroma)
library(kableExtra)
library(gridExtra)
library(cowplot)
```


```{r}

underscore_to_space <- function(x) str_replace_all(x, "_", " ")
underscore_to_space_initial_cap <- function(x) str_replace_all(x, "_", " ") %>% str_to_sentence()

```

```{r}

outliers <- read_tsv("../input_data/druggable_outliers_from_treehouse_and_other_cohorts_2023_11_09-13_46_32_2023.tsv") %>%
  mutate(high_level_cohort = ifelse(str_detect(comparison_cohort, "Treehouse"),
                                    "Treehouse",
                                    comparison_cohort))

         
n_distinct(outliers$Sample_ID)       
n_distinct(outliers$donor_ID)
```

# Define cohort codes
```{r}

cohort_codes <- tibble(
  cohort_name = 
    c("PEDAYA", "TCGA", "TH03_TH34", "Treehouse_pc", "Treehouse_pd"),
  cohort_code = 
    c("P", "T", "S", "C", "D"))

```

# Tile plot of all outliers
```{r fig.height=10, fig.width=10}

ggplot(outliers) +
  geom_tile(aes(x=comparison_cohort,
                y=gene, 
                fill = comparison_cohort)) +
  facet_wrap(~Sample_ID,
             nrow = 1) +
  theme(#axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
    axis.text.x = element_blank(),
    strip.text.x = element_text(angle = 90),
        ) +
  xlab("")  +
  scale_fill_bright()

  
```

# Heatmap shows number of cohorts in which outlier were  detected
I can make this look better if we decide to use it, but it's non-trivial
```{r fig.height=10, fig.width=6}
outliers_heatmap_data <- outliers %>%
  group_by(Sample_ID, gene) %>%
  summarize(n_outliers = n()) 

ggplot(outliers_heatmap_data) +
  geom_tile(aes(x=Sample_ID,
                y=gene,
                fill = n_outliers), 
            color = "black")  +
  #theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) 


```


```{r}
library(ggVennDiagram)

update_strings <- function(x) {
  str_replace(x,
              "PEDAYA", 
              "Pediatric") %>%
    str_replace("TH03_TH34",
                "Stanford")%>%
    str_replace("Treehouse_pc",
                "Treehouse pan-cancer")%>%
    str_replace("Treehouse_pd",
                "Treehouse pan-disease")
}

raw_outliers_for_venn <- outliers %>%
  mutate(sample_gene = paste(Sample_ID, gene, sep = "_"),
         comparison_cohort = update_strings(comparison_cohort)) %>%
  arrange(comparison_cohort) %>%
  select(sample_gene, comparison_cohort) %>%
  group_split(comparison_cohort)
raw_outliers_for_venn[[1]]

list_of_outliers_for_venn <-  lapply(raw_outliers_for_venn, function(x) x %>% pull(sample_gene))
names(list_of_outliers_for_venn) <- unique(outliers$comparison_cohort) %>% update_strings %>% sort
```


# Best venn
```{r}
ggVennDiagram(list_of_outliers_for_venn,
              label = "count",
              #label_geom = "text"
              ) + 
  scale_fill_distiller(palette = "Greens", 
                       direction = 1) + 
  scale_x_continuous(expand = expansion(mult = .2)) + 
  theme(legend.position="none")

```

# other venn
```{r}
ggVennDiagram(list_of_outliers_for_venn,
              show_intersect = TRUE)

 

fill_rescale <- function(x) scales::rescale(x, to = c(0, 0.8))

fill_rescale(1:10)

ggVennDiagram(list_of_outliers_for_venn,
              label = "count",
              #label_geom = "text"
              ) + 
  scale_fill_distiller(palette = "Greens", 
                       direction = 1)



ggVennDiagram(list_of_outliers_for_venn,
              label = "count",
              #label_geom = "text"
              ) + 
  scale_fill_distiller(palette = "Spectral", 
                       direction = 1)


ggVennDiagram(list_of_outliers_for_venn) + 
  scale_fill_distiller(palette = "Reds", 
                       direction = 1)


```







```{r}
sessionInfo()
```

