---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "`r Sys.getenv('USER')`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
---
  
  
## version notes  

2023.12.20_13.42.16 - i got it to recreate the existing plot

2023.12.20_13.52.56 - update text


```{r setup, include = FALSE}

library(tidyverse)
library(networkD3)
library(RColorBrewer)
library(colorspace)



```


# import data
```{r}
findings_file <- "../input_data/Treehouse.Drug.Prioritization.No.Identifiers.final.03.07.21 - case_prioritization.tsv"



tx_treatments_raw <- read_tsv(findings_file, 
                              col_types = cols(.default = "c")) %>% 
   select(-TH_sampleID, -`Case #`, -Note)


length(unique(tx_treatments_raw$TH_donorID))

nodes_raw <- tibble(unnumbered_name = c(tx_treatments_raw$TH_donorID, 
                                tx_treatments_raw$`Case prioritization`, 
                                tx_treatments_raw$Reason, 
                                tx_treatments_raw$`Implementation reason for prioritized findings`)) %>% 
  na.omit() %>%
  mutate(is_donor = str_detect(unnumbered_name, "TH[R]?[0-9]{2}_[0-9]{4}")) %>%
  group_by(unnumbered_name, is_donor) %>%
  summarize(n = n())

table(nodes_raw$n)



```

# nodes in order
```{r}

nodes_in_order_for_plotting_raw <- c(  #things we want to explicitly sort
  "Prioritized",
  "Deferred",
  "Declined",
  "Implemented",
  "Not implemented",
  #Implemented category: 
  "Response",
  "Progression",
  # Not implemented
  "Rapid disease progression", 
  "Waiting for treatment approval", 
  "Therapy unavailable",
  # Deferred
  "Standard of care", 
  "No further treatment needed",
  "Treatment with more disease data", 
  # Declined
  "Evidence against Treehouse therapy", 
  "Not FDA approved")


nodes_in_order_for_color_raw <- c(  
  #positive events
  "Prioritized",
  "Implemented",
  "Response",
   #second rank events
  "Progression",
  "Not implemented",
  "Rapid disease progression", 
  # Not implemented
  "Waiting for treatment approval", 
  "Therapy unavailable",
  # deferred
  "Deferred",
  "Standard of care", 
  "No further treatment needed",
  "Treatment with more disease data", 
  "Declined",
  "Evidence against Treehouse therapy", 
  "Not FDA approved")

```


# Update language
```{r}

update_names <- function(x) {
  str_replace_all(x, "Standard of care", 
                  "Received therapy considered standard of care") %>%
  str_replace_all("Treatment with more disease data", 
                  "Received therapy with more published evidence of efficacy") %>%
      str_replace_all("Evidence against Treehouse therapy", 
                  "Evidence against therapy identified by CARE analysis")
}


```


# assemble data in format required for sankey plot
```{r}

updated_nodes <- nodes_raw %>%
  mutate(unnumbered_names_for_plotting = factor(unnumbered_name, levels = nodes_in_order_for_plotting_raw),
         unnumbered_names_for_color = factor(unnumbered_name, levels = nodes_in_order_for_color_raw),
         updated_unnumbered_name = update_names(unnumbered_name),
         name = ifelse(is_donor, 
                        updated_unnumbered_name,
                        paste0(unnumbered_name, " (n=", n, ")"))) %>%
  arrange(!is_donor, unnumbered_names_for_plotting) %>%
  ungroup %>%
  mutate(node = 0:(n()-1)) 

# nodes_in_order_for_plotting <- updated_nodes_raw %>%
#   arrange(names_for_plotting) %>%
#   pull(label)
  
nodes_in_order_for_color <- updated_nodes %>%
  arrange(unnumbered_names_for_color) %>%
  pull(name)

nodes <- updated_nodes %>%
  select(name, unnumbered_name, node)
  
```


```{r}
# links <- source target value
donor_to_prioritization <- tx_treatments %>%
  select(TH_donorID, `Case prioritization`) %>%
  left_join(nodes, by=c("TH_donorID"="name")) %>%
              rename(source = node) %>%
  left_join(nodes, by=c(`Case prioritization`="unnumbered_name")) %>%
              rename(target = node) %>%
  mutate(value = 1)
  
prioritization_to_reason <- tx_treatments %>%
  select(`Case prioritization`, Reason) %>%
  left_join(nodes, by=c("Case prioritization"="unnumbered_name")) %>%
              rename(source = node) %>%
  left_join(nodes, by=c("Reason"="unnumbered_name")) %>%
              rename(target = node) %>%
  mutate(value = 1)

nodes %>%
  filter(unnumbered_name == "Received therapy with more published evidence of efficacy")

reason_to_implementation <-  tx_treatments %>%
  select(Reason, `Implementation reason for prioritized findings`) %>%
  left_join(nodes, by=c("Reason"="unnumbered_name")) %>%
              rename(source = node) %>%
  left_join(nodes, by=c("Implementation reason for prioritized findings"="unnumbered_name")) %>%
              rename(target = node) %>%
  mutate(value = 1) %>%
  na.omit

links_noisy <- bind_rows(donor_to_prioritization,
                   prioritization_to_reason,
                   reason_to_implementation) 

links <- links_noisy %>%
  select(source, target, value) %>%
  arrange(source, target, value)

sample_id_placeholder <- ""

# nodes_wo_sample_names <- nodes %>%
#    mutate(name2  = name)
nodes_wo_sample_names <- nodes %>%
#  mutate(name2 = name)
  mutate(label2 = case_when(str_detect(label, "^TH[0-9]") ~ sample_id_placeholder,
            TRUE ~ label))
  

```

# define colors
```{r}

names_to_color_blue <- tibble(name = c("Prioritized", "Implemented", "Response"), 
                              color_code = brewer.pal(name="Blues",n=6)[3:5])

sample_box_colors <- tibble(name = sample_id_placeholder,
                            color_code = "#D3D3D3")

node_names <- tibble(name = unique(nodes_wo_sample_names$label2)) %>%
  filter(! name %in% c(names_to_color_blue$name, sample_box_colors$name)) %>%
  mutate(name_f = factor(name, levels = nodes_in_order_for_color)) %>%
  arrange(name_f) %>%
  mutate(color_code = heat_hcl(n(),rev=TRUE, c=c(60,20),l=c(60,100),power=1)) %>%
  bind_rows(names_to_color_blue) %>%
  bind_rows(sample_box_colors)

color_specification <- JS(
sprintf(
'd3.scaleOrdinal()  
  .domain(%s)
  .range(%s)
',
jsonlite::toJSON(node_names$name),
jsonlite::toJSON(node_names$color_code)
   )
  )

```


# check for overlap in colors and names
```{r}
setdiff(node_names$name, nodes_wo_sample_names$name2) # expected output: character(0)
setdiff(nodes_wo_sample_names$name2, node_names$name) # expected output: character(0)

```

# plot
```{r}

networkD3::sankeyNetwork(Links = links, Nodes = nodes_wo_sample_names, Source = 'source', 
                         Target = 'target', Value = 'value', NodeID = 'name2',
                         units = '',
  sinksRight = FALSE,
  nodeWidth = 40,
  fontSize = 13,
  nodePadding = 5,
  iterations = 10,
  colourScale = color_specification)

```


