---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "`r Sys.getenv('USER')`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
---
  
  
## version notes  

2023.12.20_13.42.16 - i got it to recrearte the existing plot



```{r setup, include = FALSE}

library(tidyverse)
library(networkD3)
library(RColorBrewer)
library(colorspace)



```


# import data
```{r}
findings_file <- "../input_data/Treehouse.Drug.Prioritization.No.Identifiers.final.03.07.21 - case_prioritization.tsv"



tx_treatments_raw <- read_tsv(findings_file, 
                              col_types = cols(.default = "c")) %>% 
   select(-TH_sampleID, -`Case #`, -Note)


length(unique(tx_treatments_raw$TH_donorID))
```


# nodes in order
```{r}

nodes_in_order_for_plotting <- c(  #things we want to explicitly sort
  "Prioritized",
  "Deferred",
  "Declined",
  "Implemented",
  "Not implemented",
  #Implemented category: 
  "Response",
  "Progression",
  # Not implemented
  "Rapid disease progression", 
  "Waiting for treatment approval", 
  "Therapy unavailable",
  # Deferred
  "Standard of care", 
  "No further treatment needed",
  "Treatment with more disease data", 
  # Declined
  "Evidence against Treehouse therapy", 
  "Not FDA approved")


nodes_in_order_for_color <- c(  #positive events
  "Prioritized",
  "Implemented",
  "Response",
   #second rank events
  "Progression",
  "Not implemented",
  "Rapid disease progression", 
  # Not implemented
  "Waiting for treatment approval", 
  "Therapy unavailable",
  # deferred
  "Deferred",
  "Standard of care", 
  "No further treatment needed",
  "Treatment with more disease data", 
  "Declined",
  "Evidence against Treehouse therapy", 
  "Not FDA approved")

```


# function to update node names

```{r}

update_names <- function(x) {
  str_replace_all(x, "Standard of care", 
                  "Received therapy considered standard of care") %>%
  str_replace_all("Treatment with more disease data", 
                  "Received therapy with more published evidence of efficacy") %>%
      str_replace_all("Evidence against Treehouse therapy", 
                  "Evidence against therapy identified by CARE analysis") %>%
    str_replace_all("Prioritized",
                    "Accepted; prioritized") %>%
    str_replace_all("Deferred",
                    "Accepted; deferred")
}

```



# assemble NODE data in format required for sankey plot
```{r}

all_nodes <- tibble(name = c(tx_treatments_raw$TH_donorID, 
                                tx_treatments_raw$`Case prioritization`, 
                                tx_treatments_raw$Reason, 
                                tx_treatments_raw$`Implementation reason for prioritized findings`)) %>% 
  na.omit()

node_labels <- all_nodes  %>%
  mutate(is_donor = str_detect(name, "TH[R]?[0-9]{2}_[0-9]{4}")) %>%
  rename(unnumbered_name = name) %>%
  group_by(is_donor, unnumbered_name) %>%
  summarize(n = n()) %>%
  mutate(name_with_number = ifelse(is_donor,
                       unnumbered_name,
                       paste0(update_names(unnumbered_name), " (n=", n, ")")))



sample_id_placeholder <- ""



nodes <- all_nodes %>%
  distinct() %>%
  mutate(name_factor = factor(name) %>% 
           fct_relevel(c(tx_treatments_raw$TH_donorID,
                         nodes_in_order_for_plotting))) %>%
  arrange(name_factor) %>%
  mutate(node = 0:(n()-1)) %>%
  left_join(node_labels, by=c("name" = "unnumbered_name")) %>%
  mutate(name2 = ifelse(is_donor,
                       sample_id_placeholder,
                       name_with_number))



```

# assemble LINK data in format required for sankey plot
```{r}
# links <- source target value
donor_to_prioritization <- tx_treatments_raw %>%
  select(TH_donorID, `Case prioritization`) %>%
  left_join(nodes, by=c("TH_donorID"="name")) %>%
              rename(source = node) %>%
  left_join(nodes, by=c(`Case prioritization`="name")) %>%
              rename(target = node) %>%
  mutate(value = 1)
  
prioritization_to_reason <- tx_treatments_raw %>%
  select(`Case prioritization`, Reason) %>%
  left_join(nodes, by=c("Case prioritization"="name")) %>%
              rename(source = node) %>%
  left_join(nodes, by=c("Reason"="name")) %>%
              rename(target = node) %>%
  mutate(value = 1)

reason_to_implementation <-  tx_treatments_raw %>%
  select(Reason, `Implementation reason for prioritized findings`) %>%
  left_join(nodes, by=c("Reason"="name")) %>%
              rename(source = node) %>%
  left_join(nodes, by=c("Implementation reason for prioritized findings"="name")) %>%
              rename(target = node) %>%
  mutate(value = 1) %>%
  na.omit

links_noisy <- bind_rows(donor_to_prioritization,
                   prioritization_to_reason,
                   reason_to_implementation) 

links <- links_noisy %>%
  select(source, target, value) %>%
  arrange(source, target, value)


```

# define colors
```{r}

names_to_color_blue <- tibble(name = c("Prioritized", "Implemented", "Response") %>% update_names, 
                              blue_color_code = c("#9ECAE1", "#6BAED6", "#3182BD"))
# brewer.pal(name="Blues",n=6)[3:5])


sample_box_colors <- tibble(name = sample_id_placeholder,
                            color_code = "#D3D3D3")


node_names <- nodes %>%
  # filter(! is_donor,
  #        ! name %in% c(names_to_color_blue$name, sample_box_colors$name)) %>%
  mutate(name_f = factor(name, levels = nodes_in_order_for_color)) %>%
  arrange(name_f) %>%
  mutate(color_code_base = heat_hcl(n(),rev=TRUE, c=c(60,20),l=c(60,100),power=1)) %>%
  left_join(names_to_color_blue, by = "name") %>%
  mutate(color_code = case_when(
    is.na(name_f) ~ sample_box_colors$color_code,
    !is.na(blue_color_code) ~ blue_color_code,
    TRUE ~ color_code_base)) %>%
  select(name, name_f, blue_color_code, color_code) %>%
  left_join(nodes %>% 
              select(name, name2))

node_names_for_color_spec <- 
  node_names %>%
  select(name2, color_code) %>%
  distinct()

color_specification <- JS(
sprintf(
'd3.scaleOrdinal()  
  .domain(%s)
  .range(%s)
',
jsonlite::toJSON(node_names_for_color_spec$name2),
jsonlite::toJSON(node_names_for_color_spec$color_code)
   )
  )

```


# check for overlap in colors and names
```{r}

setdiff(node_names$name, nodes_wo_sample_names$name2) # expected output: character(0)
setdiff(nodes_wo_sample_names$name2, node_names$name) # expected output: character(0)

```


# combine all data
```{r}

networkD3_data <- list(nodes = list(name = nodes$name),
                       links = list(source = links$source,
                                    target = links$target, 
                                    value = links$value)
)

sankeyNetwork(Links = networkD3_data$links, 
              Nodes = networkD3_data$nodes, 
              Source = "source", 
              Target = "target", 
              Value = "value", 
              NodeID = "name", 
              #NodeGroup="group", 
              fontSize=14 
              #colourScale="colors")
)

```


```{r}
sankeyNetwork(Links = networkD3_data$links, Nodes = networkD3_data$nodes, Source = "source", Target = "target", Value = "value", NodeID = "name", NodeGroup="group", fontSize=14, colourScale="colors")
```

# plot
```{r fig.height=6, fig.width=10}

networkD3::sankeyNetwork(Links = links, 
                         Nodes = nodes %>%
                           select(name2, node), 
                         Source = 'source', 
                         Target = 'target', 
                         Value = 'value', 
                         NodeID = 'name2',
#                         NodeGroup = 'name2',
                         units = '',
                         sinksRight = FALSE,
                         nodeWidth = 40,
                         fontSize = 13,
                         nodePadding = 5,
                         iterations = 10,
                         width = 1000,
                         colourScale = color_specification)


```
```{r}

# library(networkD3)
# library(htmlwidgets)
# library(data.table)
# 
# set.seed(1999)
# links <- data.table(
#   src = rep(0:4, times=c(1,1,2,3,5)),
#   target = sample(1:11, 12, TRUE),
#   value = sample(100, 12)
# )[src < target, ]  # no loops
# nodes <- data.table(name=LETTERS[1:12])
# 
# ## Add text to label
# txt <- links[, .(total = sum(value)), by=c('target')]
# nodes[txt$target+1L, name := paste0(name, '<br>(', txt$total, ')')]
# 
# ## Displays the counts as part of the labels
# sn <- sankeyNetwork(Links=links, Nodes=nodes, Source='src', Target='target',
#               Value='value', NodeID='name', fontSize=16, width=600, height=300)
# 
# onRender(sn,
#          '
#   function(el,x) {
#     d3.selectAll(".node text").remove()
#     d3.selectAll(".node")
#       .append("foreignObject")
#       .attr("width", 100)
#       .attr("height", 50)
#       .html(function(d) { return d.name; })
#   }
#   '
# )
```

```{r}
sessionInfo()
```

