---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "`r Sys.getenv('USER')`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
---
  
# version notes

version 2023.11.06_11.32.08 is for troubleshooting how many values are in Molecular Category

```{r setup, include = FALSE}

library(tidyverse)
library(knitr)
library(janitor)
library(kableExtra)
```


# Load and combine data
```{r}


findings_file <- "../input_data/Supplementary_Tables - eTable8_dl_2023.11.06_11.03.03.tsv"

findings <- read_tsv(findings_file,
                     skip = 1) %>%
  rename(donorID = `Patient ID`)

```


```{r}

latest_sample_metadata_file_name <- "../input_data/ckcc2_samples_and_metadata_from_redcap_2023.10.24_13.26.34.tsv"

sample_metadata <- read_tsv(latest_sample_metadata_file_name,
                            col_types = cols(.default = "c")) %>%
  mutate(dx_group_factor = fct_lump_min(dx_group, 2),
         dx_group = as.character(dx_group_factor))

donor_disease <- sample_metadata %>%
  select(donorID, disease, dx_group, age_at_dx, gender) %>%
  distinct() 

```




```{r}

findings_with_metadata <- left_join(
  findings,
  donor_disease,
  by = "donorID")

```


```{r}

findings_with_metadata %>%
  tabyl(`Molecular Category`) %>%
  adorn_pct_formatting() %>%
  kbl() %>%
  kable_styling(full_width = F)

```


## Load gene and disease groups 
```{r}

gene_group_info <- read_tsv("../input_data/gene_group_info.tsv", col_types = cols(.default = "c"))

disease_group_names <- read_tsv(file.path("../input_data/", "disease_group_info.tsv"), col_types = cols(.default = "c"))

```
# expected gene groups
```{r}

gene_group_info %>%
  select(outlier_gene_group) %>% 
  kbl(format.args = list(big.mark = ","), digits = c(NA, NA, 4, 4, 3, 2)) %>%
  kable_styling(full_width = F)

```

```{r}
pre_defined_arms <- c("JAK/STAT","RTK", "Cell Cycle", "PI3K/AKT/mTOR")
pre_defined_arms
```



# View gene set colors
```{r}

gene_group_info %>%
  mutate(gene_group_color = cell_spec(
    gene_group_color, color = "white", bold = T,
    background = gene_group_color
  )) %>%
  kable(escape = F, align = "c") %>%
  kable_styling(c("striped", "condensed"), full_width = F)
  

```

# Session Info
```{r}
sessionInfo()
```

# Appendix

## Full findings table
```{r}

findings %>%
  select(donorID, Drug, `Molecular Abnormality`, `Molecular Category`) %>%
  kbl() %>%
  kable_styling(full_width = F)
```

